### ISSUE TITLE
Cups est désormais lancé par un nouveau service.

### ISSUE THREAD

**Issue by FredBezies** [Chennux/arch-tuto-installation#1]
Bonjour.

Cups s'active désormais avec le service cups.service au lieu de org.cups.cupsd. Modification qui date du 20 novembre.

https://github.com/archlinux/svntogit-packages/commit/104686c89c71b81d40e07bc92bb7c70264de3d88#diff-3e341d2d9c67be01819b25b25d5e53ea3cdf3a38d28846cda85a195eb9b7203a

**Comment by Chennux** [comment]
Bonjour,
La modification a été apportée. Je l'avais déjà notée mais tu as quand même bien fait de me le rappeler pour que je l'insère plus rapidement. ;-)
